name: CD

on:
  push:
    branches: [main]
  workflow_dispatch: # manual trigger button

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    # Needed to push to GHCR
    permissions:
      contents: read
      packages: write

    steps:
      - uses: actions/checkout@v4

      # Set up Docker Buildx (multi-arch builder)
      - uses: docker/setup-buildx-action@v3

      # --- LOGIN to registry ---------------------
      # Option A: GHCR  (uses built-in GITHUB_TOKEN)
      - name: Login to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      ##  Option B: Docker Hub (comment GHCR block above, uncomment below)
      # - name: Login to Docker Hub
      #   uses: docker/login-action@v3
      #   with:
      #     registry: docker.io
      #     username: ${{ secrets.DOCKERHUB_USER }}
      #     password: ${{ secrets.DOCKERHUB_TOKEN }}
      # -------------------------------------------

      # Build + push image
      #   - name: Build and push
      #     uses: docker/build-push-action@v5
      #     with:
      #       push: true
      #       tags: |
      #         ghcr.io/${{ github.repository }}:latest
      #         ghcr.io/${{ github.repository }}:${{ github.sha::7 }}
      #       # If using Docker Hub:
      #       # tags: |
      #       #   ${{ secrets.DOCKERHUB_USER }}/mini-rec-ab:latest
      #       #   ${{ secrets.DOCKERHUB_USER }}/mini-rec-ab:${{ github.sha::7 }}

      # OPTIONAL: deploy to remote host via SSH and restart container
    #   - name: Deploy on VPS # remove if not needed
    #     if: success()
    #     uses: appleboy/ssh-action@v1
    #     with:
    #       host: ${{ secrets.VPS_HOST }}
    #       username: ${{ secrets.VPS_USER }}
    #       key: ${{ secrets.VPS_KEY }}
    #       script: |
    #         docker pull ghcr.io/${{ github.repository }}:latest
    #         docker stop mini-rec-ab || true
    #         docker rm mini-rec-ab || true
    #         docker run -d --name mini-rec-ab -p 8000:8000 ghcr.io/${{ github.repository }}:latest
