name: CI

on:
  push:
  pull_request:

jobs:
  lint-and-test:
    runs-on: ubuntu-latest
    steps:
      # Checkout repo
      - uses: actions/checkout@v4

      # Install Python
      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      # Install dependencies
      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pytest flake8 black

      # Style check (Black in --check mode)
      - name: Black
        run: black --check .

      # Lint
      - name: Flake8
        run: flake8 .

      # Unit tests
      - name: Pytest
        run: pytest -q
